baseURL = "http://www.example.com"
languageCode = "en-us"
title = "David Large"
themesDir = "themes"
theme = "hugo-winston-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@avidlarge"

  showAuthorOnHomepage = true
  showAuthorOnPosts = true
  showPostsOnHomepage = false

  addFrame = true
  addDot = true

  highlightColor = '#5000ca'


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
